name: ceshi
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ceshi
      run: |
        sudo curl -s -L https://git.io/v2ray.sh && bash
